# Generated by Django 2.0.3 on 2019-12-08 13:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCinco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titulo', max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('plantilla', models.Field(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades Cinco',
            },
        ),
        migrations.CreateModel(
            name='ActividadCuatro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titulo', max_length=200)),
                ('name', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Actividades Cuatro',
            },
        ),
        migrations.CreateModel(
            name='ActividadDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titulo', max_length=200)),
                ('name', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Actividades Dos',
            },
        ),
        migrations.CreateModel(
            name='ActividadSeis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titulo', max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('pregunta_uno', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_dos', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_tres', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_cuatro', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_cinco', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_seis', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_siete', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_ocho', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_nueve', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_diez', models.CharField(blank=True, max_length=200, null=True)),
                ('pregunta_once', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades Seis',
            },
        ),
        migrations.CreateModel(
            name='ActividadUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titulo', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('respuesta_uno', models.CharField(blank=True, max_length=200, null=True)),
                ('respuesta_dos', models.CharField(blank=True, max_length=200, null=True)),
                ('respuesta_tres', models.CharField(blank=True, max_length=200, null=True)),
                ('respuesta_cuatro', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades Uno',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Colegios',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RespuestasCinco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.Field(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_cinco', to='web.ActividadCinco')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_cinco', to='web.Alumno')),
            ],
            options={
                'verbose_name_plural': 'Respuestas Cinco',
            },
        ),
        migrations.CreateModel(
            name='RespuestasCuatro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=500, verbose_name='Respuesta')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_cuatro', to='web.ActividadCuatro')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_cuatro', to='web.Alumno')),
            ],
            options={
                'verbose_name_plural': 'Respuestas Cuatro',
            },
        ),
        migrations.CreateModel(
            name='RespuestasDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(max_length=500, verbose_name='Respuesta')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_dos', to='web.ActividadDos')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_dos', to='web.Alumno')),
            ],
            options={
                'verbose_name_plural': 'Respuestas Dos',
            },
        ),
        migrations.CreateModel(
            name='RespuestasSeis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_uno', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_dos', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_tres', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_cuatro', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_cinco', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_seis', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_siete', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_ocho', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_nueve', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_diez', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('respuesta_once', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_seis', to='web.ActividadSeis')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_seis', to='web.Alumno')),
            ],
            options={
                'verbose_name_plural': 'Respuestas Seis',
            },
        ),
        migrations.CreateModel(
            name='RespuestasUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_uno', to='web.ActividadUno')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_uno', to='web.Alumno')),
            ],
            options={
                'verbose_name_plural': 'Respuestas Uno',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='web.Colegio'),
        ),
    ]
