# Generated by Django 2.0.3 on 2019-12-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcuatro',
            name='name',
            field=models.TextField(max_length=2050),
        ),
        migrations.AlterField(
            model_name='actividaddos',
            name='name',
            field=models.TextField(max_length=2050),
        ),
        migrations.AlterField(
            model_name='respuestascuatro',
            name='valor',
            field=models.CharField(max_length=2050, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='respuestasdos',
            name='valor',
            field=models.TextField(max_length=2050, verbose_name='Respuesta'),
        ),
    ]
