# Generated by Django 2.0.3 on 2019-12-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191209_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titulo', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('titulo_uno', models.CharField(blank=True, max_length=200, null=True)),
                ('paso_uno', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_dos', models.CharField(blank=True, max_length=200, null=True)),
                ('paso_dos', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_tres', models.CharField(blank=True, max_length=200, null=True)),
                ('paso_tres', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_cuatro', models.CharField(blank=True, max_length=200, null=True)),
                ('paso_cuatro', models.CharField(blank=True, max_length=500, null=True)),
                ('titulo_cinco', models.CharField(blank=True, max_length=200, null=True)),
                ('paso_cinco', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Actividades Tres',
            },
        ),
        migrations.CreateModel(
            name='RespuestasTres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200, verbose_name='Respuesta')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_tres', to='web.ActividadTres')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_tres', to='web.Alumno')),
            ],
            options={
                'verbose_name_plural': 'Respuestas Tres',
            },
        ),
    ]
