# Generated by Django 2.0.3 on 2019-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20191209_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcinco',
            name='plantilla',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Plantilla'),
        ),
        migrations.AlterField(
            model_name='respuestascinco',
            name='valor',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Fichero'),
        ),
    ]
